/**
 * Prebuilt runtime management for vscode-antimony.
 *
 * Replaces the old flow (install a .exe or .pkg, install Python, install git,
 * shell out to a platform-specific script, create a venv, pip install 20
 * packages, wait five minutes, hope).
 *
 * New flow: on first activation the extension downloads one tarball containing
 * a complete Python interpreter with every dependency already installed,
 * verifies its checksum, and unpacks it into the extension's own global
 * storage. No installer, no admin rights, no PATH changes, no Gatekeeper or
 * SmartScreen prompt, nothing left behind on uninstall.
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as http from 'http';
import * as https from 'https';
import * as crypto from 'crypto';
import * as tar from 'tar';

// Must match RUNTIME_VERSION in scripts/build_runtime.py.
const RUNTIME_VERSION = '1';

// GitHub Release that holds the built bundles. Tag the release
// `runtime-v<RUNTIME_VERSION>` when you publish.
const RELEASE_BASE =
  `https://github.com/sys-bio/vscode-antimony/releases/download/runtime-v${RUNTIME_VERSION}`;

/**
 * SHA-256 of each bundle, generated by build_runtime.py and committed here.
 *
 * This is what makes downloading a 90 MB executable payload safe: the digest
 * ships inside the signed .vsix, so a tampered or truncated download is
 * rejected before anything is unpacked or run. Update these whenever you cut
 * a new runtime release.
 */
const CHECKSUMS: Record<string, string> = {
  'win32-x64': 'REPLACE_WITH_SHA256_FROM_CI',
  'darwin-x64': 'REPLACE_WITH_SHA256_FROM_CI',
  'darwin-arm64': 'REPLACE_WITH_SHA256_FROM_CI',
  'linux-x64': 'REPLACE_WITH_SHA256_FROM_CI',
};

/**
 * Download and unpacked size of each bundle, in bytes. Printed by
 * build_runtime.py alongside the checksums; update both together.
 *
 * Used only for the pre-flight disk space check. Slightly generous values are
 * safer than tight ones: refusing to start on a machine that would have just
 * fit is a much smaller harm than failing halfway through unpacking.
 */
interface BundleSize { download: number; unpacked: number; }

const SIZES: Record<string, BundleSize> = {
  'win32-x64': { download: 95_000_000, unpacked: 340_000_000 },
  'darwin-x64': { download: 95_000_000, unpacked: 340_000_000 },
  'darwin-arm64': { download: 95_000_000, unpacked: 340_000_000 },
  'linux-x64': { download: 95_000_000, unpacked: 340_000_000 },
};

/** Extra room left over after install, so we don't fill the user's disk. */
const HEADROOM_BYTES = 250_000_000;

export class UnsupportedPlatformError extends Error {}

function platformKey(): string {
  const plat = os.platform();
  const arch = process.arch;

  if (plat === 'win32' && arch === 'x64') { return 'win32-x64'; }
  if (plat === 'darwin' && arch === 'x64') { return 'darwin-x64'; }
  if (plat === 'darwin' && arch === 'arm64') { return 'darwin-arm64'; }
  if (plat === 'linux' && arch === 'x64') { return 'linux-x64'; }

  throw new UnsupportedPlatformError(
    `Antimony does not ship a prebuilt runtime for ${plat}/${arch}. ` +
    `Set "vscode-antimony.pythonInterpreter" to a Python 3.10 interpreter that ` +
    `has the extension's dependencies installed.`
  );
}

function runtimeRoot(context: vscode.ExtensionContext): string {
  return path.join(context.globalStorageUri.fsPath, 'runtime', RUNTIME_VERSION);
}

function interpreterIn(root: string): string {
  return os.platform() === 'win32'
    ? path.join(root, 'python', 'python.exe')
    : path.join(root, 'python', 'bin', 'python3');
}

/** Marker written only after a complete, verified install. */
function markerIn(root: string): string {
  return path.join(root, '.installed');
}

function isInstalled(root: string): boolean {
  return fs.existsSync(markerIn(root)) && fs.existsSync(interpreterIn(root));
}

/**
 * Follow redirects manually. GitHub release assets always redirect to a CDN
 * host, and Node's https module does not follow redirects on its own.
 */
function httpsGet(url: string, redirectsLeft = 5): Promise<http.IncomingMessage> {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'User-Agent': 'vscode-antimony' } }, (res) => {
      const status = res.statusCode ?? 0;
      if (status >= 300 && status < 400 && res.headers.location) {
        res.resume();
        if (redirectsLeft <= 0) {
          reject(new Error('Too many redirects while downloading the Antimony runtime.'));
          return;
        }
        resolve(httpsGet(res.headers.location, redirectsLeft - 1));
        return;
      }
      if (status !== 200) {
        res.resume();
        reject(new Error(`Download failed with HTTP ${status}.`));
        return;
      }
      resolve(res);
    });
    req.on('error', reject);
    req.setTimeout(60_000, () => req.destroy(new Error('Download timed out.')));
  });
}

async function downloadWithProgress(
  url: string,
  dest: string,
  progress: vscode.Progress<{ message?: string; increment?: number }>,
  token: vscode.CancellationToken
): Promise<string> {
  const res = await httpsGet(url);
  const total = Number(res.headers['content-length'] ?? 0);
  const hash = crypto.createHash('sha256');

  let received = 0;
  let lastReported = 0;

  await new Promise<void>((resolve, reject) => {
    const file = fs.createWriteStream(dest);

    const fail = (err: Error) => {
      res.destroy();
      file.destroy();
      reject(err);
    };

    token.onCancellationRequested(() => fail(new Error('Cancelled.')));

    res.on('data', (chunk: Buffer) => {
      received += chunk.length;
      hash.update(chunk);
      if (total > 0) {
        const pct = Math.floor((received / total) * 100);
        if (pct > lastReported) {
          progress.report({
            increment: pct - lastReported,
            message: `Downloading Python components (${pct}%)`,
          });
          lastReported = pct;
        }
      }
    });

    res.on('error', fail);
    file.on('error', fail);
    file.on('finish', () => resolve());
    res.pipe(file);
  });

  return hash.digest('hex');
}

function formatBytes(bytes: number): string {
  const gb = bytes / 1_073_741_824;
  if (gb >= 1) { return `${gb.toFixed(1)} GB`; }
  return `${Math.round(bytes / 1_048_576)} MB`;
}

/** Bytes a non-privileged user can actually write to the volume holding `dir`. */
async function availableBytes(dir: string): Promise<number | null> {
  // fs.statfs landed in Node 18.15. Older VS Code builds ship less than that,
  // so treat its absence as "cannot tell" rather than as an error. Skipping the
  // check degrades to the previous behaviour; it never blocks a valid install.
  const statfs = (fs.promises as any).statfs;
  if (typeof statfs !== 'function') { return null; }

  try {
    // bavail, not bfree: bfree includes root-reserved blocks the user cannot touch.
    const st = await statfs(dir);
    return Number(st.bavail) * Number(st.bsize);
  } catch {
    return null;
  }
}

/** True if both paths sit on the same filesystem, so their needs add up. */
function sameVolume(a: string, b: string): boolean {
  try {
    return fs.statSync(a).dev === fs.statSync(b).dev;
  } catch {
    return false;
  }
}

/**
 * Refuse to start an install that cannot finish.
 *
 * Two distinct volumes are involved and they are often different: the archive
 * lands in the OS temp directory, and it is unpacked into global storage. On a
 * machine with a small system partition, either one can be the constraint.
 *
 * Throws with a message naming the actual shortfall. Returns silently when
 * space cannot be determined.
 */
async function assertEnoughSpace(key: string, tmpDir: string, targetDir: string): Promise<void> {
  const size = SIZES[key];
  if (!size) { return; }

  const shared = sameVolume(tmpDir, targetDir);

  // While unpacking, the archive is still on disk: peak usage is both at once.
  const needTmp = shared ? 0 : size.download;
  const needTarget = shared
    ? size.download + size.unpacked + HEADROOM_BYTES
    : size.unpacked + HEADROOM_BYTES;

  const checks: Array<{ dir: string; need: number; label: string }> = [
    { dir: targetDir, need: needTarget, label: 'Antimony installs its components to' },
  ];
  if (!shared) {
    checks.push({ dir: tmpDir, need: needTmp + HEADROOM_BYTES, label: 'the temporary folder at' });
  }

  for (const check of checks) {
    const free = await availableBytes(check.dir);
    if (free === null) { continue; }
    if (free < check.need) {
      throw new Error(
        `Not enough free disk space. ${check.label} ${check.dir}, which needs about ` +
        `${formatBytes(check.need)} free but has ${formatBytes(free)}. ` +
        `Free up some space and try again.`
      );
    }
  }
}

/**
 * Ensure a usable interpreter exists and return its absolute path.
 *
 * Resolution order:
 *   1. An explicit user override in settings (power users, Linux on odd
 *      architectures, lab machines with a curated environment).
 *   2. An already-installed bundled runtime.
 *   3. Download and install the bundled runtime.
 */
export async function ensureRuntime(context: vscode.ExtensionContext): Promise<string | null> {
  const override = vscode.workspace
    .getConfiguration('vscode-antimony')
    .get<string>('pythonInterpreter', '')
    .trim();

  if (override) {
    return override;
  }

  let key: string;
  try {
    key = platformKey();
  } catch (err) {
    vscode.window.showErrorMessage((err as Error).message);
    return null;
  }

  const root = runtimeRoot(context);
  if (isInstalled(root)) {
    return interpreterIn(root);
  }

  await cleanupOldRuntimes(context);

  const url = `${RELEASE_BASE}/antimony-runtime-${RUNTIME_VERSION}-${key}.tar.gz`;
  const expected = CHECKSUMS[key];
  const staging = `${root}.tmp-${process.pid}`;
  const archive = path.join(os.tmpdir(), `antimony-runtime-${process.pid}.tar.gz`);

  try {
    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: 'Setting up Antimony (one time)',
        cancellable: true,
      },
      async (progress, token) => {
        // Create the target first: statfs needs a path that exists, and this
        // also surfaces a permissions problem before spending a 95 MB download.
        fs.mkdirSync(path.dirname(root), { recursive: true });

        progress.report({ message: 'Checking available disk space' });
        await assertEnoughSpace(key, os.tmpdir(), path.dirname(root));

        const actual = await downloadWithProgress(url, archive, progress, token);

        if (expected && expected !== 'REPLACE_WITH_SHA256_FROM_CI' && actual !== expected) {
          throw new Error(
            'The downloaded Antimony components did not match their expected ' +
            'checksum. The download may have been corrupted or interfered with. ' +
            'Nothing was installed.'
          );
        }

        progress.report({ message: 'Unpacking' });

        fs.rmSync(staging, { recursive: true, force: true });
        fs.mkdirSync(staging, { recursive: true });

        // tar (the npm package) preserves the executable bit on the
        // interpreter, which a naive unzip does not.
        await tar.x({ file: archive, cwd: staging });

        if (!fs.existsSync(interpreterIn(staging))) {
          throw new Error('The Antimony runtime archive was missing its interpreter.');
        }

        // Rename last, so a killed or failed install never leaves a
        // half-unpacked directory that looks valid on the next launch.
        fs.rmSync(root, { recursive: true, force: true });
        fs.renameSync(staging, root);
        fs.writeFileSync(markerIn(root), `${RUNTIME_VERSION}\n${actual}\n`, 'utf8');
      }
    );
  } catch (err) {
    fs.rmSync(staging, { recursive: true, force: true });
    const message = (err as Error).message ?? String(err);

    if (message === 'Cancelled.') {
      vscode.window.showInformationMessage(
        'Antimony setup was cancelled. Run "Antimony: Reinstall Components" when you are ready.'
      );
      return null;
    }

    const choice = await vscode.window.showErrorMessage(
      `Antimony could not finish setting up: ${message}`,
      'Try again',
      'Open logs'
    );
    if (choice === 'Try again') {
      return ensureRuntime(context);
    }
    if (choice === 'Open logs') {
      vscode.commands.executeCommand('workbench.action.toggleDevTools');
    }
    return null;
  } finally {
    fs.rmSync(archive, { force: true });
  }

  return interpreterIn(root);
}

/** Remove runtimes from older RUNTIME_VERSIONs so upgrades do not accumulate. */
async function cleanupOldRuntimes(context: vscode.ExtensionContext): Promise<void> {
  const base = path.join(context.globalStorageUri.fsPath, 'runtime');
  if (!fs.existsSync(base)) { return; }
  for (const entry of fs.readdirSync(base)) {
    if (entry !== RUNTIME_VERSION) {
      fs.rmSync(path.join(base, entry), { recursive: true, force: true });
    }
  }
}

/**
 * Replacement for the old "Delete Virtual Environment to Fix Vscode-Antimony"
 * command. Wipes the runtime and reinstalls it.
 */
export async function reinstallRuntime(context: vscode.ExtensionContext): Promise<void> {
  const base = path.join(context.globalStorageUri.fsPath, 'runtime');
  fs.rmSync(base, { recursive: true, force: true });

  const interpreter = await ensureRuntime(context);
  if (!interpreter) { return; }

  const choice = await vscode.window.showInformationMessage(
    'Antimony components reinstalled. Reload to finish.',
    'Reload'
  );
  if (choice === 'Reload') {
    vscode.commands.executeCommand('workbench.action.reloadWindow');
  }
}